#!/usr/bin/env node
const fs = require('fs');

const file = process.argv[2]

if (!file) {
    const helpMessage = 'Usage: [node] unwrap.js <FILE>'
    process.stdout.write(helpMessage)
    return;
}

const data = JSON.parse(fs.readFileSync(file, {encoding: 'utf8', flag: 'r'}));
const res = [];

for (const attr in data) {
    res.push({name: attr, ...data[attr]})
}

process.stdout.write(JSON.stringify(res))